FROM r-base:4.2.2

RUN mkdir /scratch
RUN mkdir /data

RUN apt-get update -qq
RUN apt-get install -y libcurl4-openssl-dev 
RUN apt-get install -y libcurl4-gnutls-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y libhdf5-dev
RUN apt-get install -y librtmp-dev 
RUN apt-get install -y libfontconfig1-dev 
RUN apt-get install -y libxml2-dev
