FROM shengqh/bioinfo:java1.8.0_perl5.22.1_r3.6.1_python3.7.3

RUN pip install --upgrade pip

RUN pip install git+https://github.com/linlabcode/bamliquidator-batch.git

RUN pip install git+https://github.com/linlabbcm/bamplot.git

RUN pip install git+https://github.com/linlabcode/pipeline-tools.git@enhancerPromoter  -U

RUN pip install git+https://github.com/linlabcode/CRC.git
