FROM us.gcr.io/broad-gotc-prod/imputation-bcf-vcf:1.0.7-1.10.2-0.1.16-1669908889

RUN cd /usr/local/bin && wget https://raw.githubusercontent.com/shengqh/agd_vcf/refs/heads/main/agd_vcf && chmod +x agd_vcf
